//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessory
    {
        public int ac_ID { get; set; }
        public string product_id { get; set; }
        public Nullable<int> para_id { get; set; }
        public string content { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual parameter parameter { get; set; }
    }
}
