//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int comID { get; set; }
        public string proID { get; set; }
        public Nullable<int> cusID { get; set; }
        public string comMessage { get; set; }
        public Nullable<System.DateTime> comDate { get; set; }
        public string cusemail { get; set; }
        public string cusName { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
