//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_LaptopEntities : DbContext
    {
        public QL_LaptopEntities()
            : base("name=QL_LaptopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accessory> accessories { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<CancelOrder> CancelOrders { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customertype> Customertypes { get; set; }
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<Detail> Details { get; set; }
        public virtual DbSet<DetailsOrder> DetailsOrders { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeesRole> EmployeesRoles { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<NameOrderStatu> NameOrderStatus { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<parameter> parameters { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductType> ProductTypes { get; set; }
        public virtual DbSet<promotion> promotions { get; set; }
        public virtual DbSet<PromotionsGift> PromotionsGifts { get; set; }
        public virtual DbSet<TitleDetailAccessory> TitleDetailAccessories { get; set; }
        public virtual DbSet<Trademark> Trademarks { get; set; }
    
        public virtual int auto_idAccessory(ObjectParameter id)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("auto_idAccessory", id);
        }
    
        public virtual int auto_idProducts(ObjectParameter id)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("auto_idProducts", id);
        }
    
        public virtual int LayMa(ObjectParameter ma)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LayMa", ma);
        }
    }
}
